default_agent: trade_extraction_agent
agents:
  trade_extraction_agent:
    name: trade_extraction_agent
    entrypoint: /Users/koushald/ai-trade-matching-system/deployment/trade_extraction/trade_extraction_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/koushald/ai-trade-matching-system/deployment/trade_extraction
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-18b6840951
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-401552979575-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: trade_extraction_agent-KnAx4O4ezw
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/trade_extraction_agent-KnAx4O4ezw
      agent_session_id: 78a76ec4-1a30-40be-8b76-74591538702e
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: trade_extraction_agent_mem-jpnvtz4Ywn
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:memory/trade_extraction_agent_mem-jpnvtz4Ywn
      memory_name: trade_extraction_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
