default_agent: agent_matching_ai
agents:
  agent_matching_ai:
    name: agent_matching_ai
    entrypoint: /Volumes/FastSSD/Projects/agentic-ai-reconcillation/deployment/trade_extraction/agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Volumes/FastSSD/Projects/agentic-ai-reconcillation/deployment/trade_extraction
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-211bc0c422
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: 401552979575.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-agent_matching_ai
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agent_matching_ai-KrY5QeCyXe
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/agent_matching_ai-KrY5QeCyXe
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-agent_matching_ai-builder
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-211bc0c422
      source_bucket: bedrock-agentcore-codebuild-sources-401552979575-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: TradeMatchingMemory-5f8wTKHzCs
      memory_arn: null
      memory_name: agent_matching_ai_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
