default_agent: orchestrator_otc
agents:
  orchestrator_agent:
    name: orchestrator_agent
    entrypoint: /Users/koushald/ai-trade-matching-system-2/deployment/orchestrator/orchestrator_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/koushald/ai-trade-matching-system-2/deployment/orchestrator
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-00cafffea8
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-401552979575-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: orchestrator_agent-dMq9FIHJ7t
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/orchestrator_agent-dMq9FIHJ7t
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: orchestrator_agent_mem-PGYCwz5E78
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:memory/orchestrator_agent_mem-PGYCwz5E78
      memory_name: orchestrator_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  orchestrator_otc:
    name: orchestrator_otc
    entrypoint: /Users/koushald/ai-trade-matching-system-2/deployment/orchestrator/orchestrator_agent_strands.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/koushald/ai-trade-matching-system-2/deployment/orchestrator
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-6e5e65b133
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: 401552979575.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-orchestrator_otc
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: orchestrator_otc-X4XXQWCzQF
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/orchestrator_otc-X4XXQWCzQF
      agent_session_id: b08992b0-63ac-41d9-a688-6f629eeb7007
    codebuild:
      project_name: bedrock-agentcore-orchestrator_otc-builder
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-6e5e65b133
      source_bucket: bedrock-agentcore-codebuild-sources-401552979575-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: orchestrator_otc_mem-ViZKrl7gg2
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:memory/orchestrator_otc_mem-ViZKrl7gg2
      memory_name: orchestrator_otc_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
