# AgentCore configuration for Orchestrator Agent

agent:
  name: orchestrator-agent
  description: Monitors SLAs, enforces compliance, and coordinates agent workflows
  version: 1.0.0
  
runtime:
  type: PYTHON_3_11
  entry_point: orchestrator_agent.py
  handler: invoke
  timeout: 180  # 3 minutes for monitoring
  memory_mb: 2048
  
environment:
  AWS_REGION: us-east-1
  S3_BUCKET_NAME: trade-matching-bucket
  DYNAMODB_AGENT_REGISTRY_TABLE: AgentRegistry
  LOG_LEVEL: INFO
  
memory:
  enabled: true
  strategy: semantic
  retention_days: 90
  
scaling:
  min_instances: 1
  max_instances: 5
  target_utilization: 0.6
  
sla:
  processing_time_seconds: 10
  throughput_per_hour: 600
  error_rate_threshold: 0.01
  
event_subscriptions:
  - queue: orchestrator-monitoring-queue
    batch_size: 10
    visibility_timeout: 180
    
event_publications:
  - queue: control-commands-queue
    event_type: CONTROL_COMMAND_ISSUED
  - queue: alert-queue
    event_type: SLA_VIOLATED
