default_agent: exception_manager
agents:
  exception_management_agent:
    name: exception_management_agent
    entrypoint: /Volumes/FastSSD/Projects/agentic-ai-reconcillation/deployment/exception_management/exception_management_agent.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Volumes/FastSSD/Projects/agentic-ai-reconcillation/deployment/exception_management
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-116b035397
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-401552979575-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: exception_management_agent-QrSzPSChxP
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/exception_management_agent-QrSzPSChxP
      agent_session_id: ef45bb50-e3c1-4d8c-9538-badd61f7ed75
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: exception_management_agent_mem-GVHALbBeKr
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:memory/exception_management_agent_mem-GVHALbBeKr
      memory_name: exception_management_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
  exception_manager:
    name: exception_manager
    entrypoint: /Volumes/FastSSD/Projects/agentic-ai-reconcillation/deployment/exception_management/exception_management_agent_strands.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Volumes/FastSSD/Projects/agentic-ai-reconcillation/deployment/exception_management
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-0f9cb91bfb
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: 401552979575.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-exception_manager
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: exception_manager-uliBS5DsX3
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/exception_manager-uliBS5DsX3
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-exception_manager-builder
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-18b6840951
      source_bucket: bedrock-agentcore-codebuild-sources-401552979575-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: exception_management_agent_mem-GVHALbBeKr
      memory_arn: null
      memory_name: exception_manager_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
