default_agent: trade_matching_swarm_agentcore_http
agents:
  trade_matching_swarm_agentcore_http:
    name: trade_matching_swarm_agentcore_http
    entrypoint: /Users/koushald/ai-trade-matching-system/deployment/swarm_agentcore/trade_matching_swarm_agentcore_http.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/koushald/ai-trade-matching-system/deployment/swarm_agentcore
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-116b035397
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: 401552979575.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-trade_matching_swarm_agentcore_http
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: trade_matching_swarm_agentcore_http-PJeubFHvY3
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/trade_matching_swarm_agentcore_http-PJeubFHvY3
      agent_session_id: 4c0a018e-02ff-441f-85f6-075bf7b61aca
    codebuild:
      project_name: bedrock-agentcore-trade_matching_swarm_agentcore_http-builder
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-116b035397
      source_bucket: bedrock-agentcore-codebuild-sources-401552979575-us-east-1
    memory:
      mode: STM_AND_LTM
      memory_id: TradeMatchingMemory-5f8wTKHzCs
      memory_arn: null
      memory_name: trade_matching_swarm_agentcore_http_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
