AWSTemplateFormatVersion: '2010-09-09'
Description: 'Trade Reconciliation Solution - API Gateway and Lambda Functions'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  ApiStageName:
    Type: String
    Default: api
    Description: Name of the API Gateway stage
  
  CognitoUserPoolArn:
    Type: String
    Description: ARN of the Cognito User Pool for API authentication
    Default: ''
  
  # AI Provider Configuration Parameters
  AIProviderType:
    Type: String
    Default: bedrock
    Description: AI provider type for enhanced reconciliation
  
  DecisionMode:
    Type: String
    Default: deterministic
    Description: Decision making approach for trade reconciliation
  
  AIProviderRegion:
    Type: String
    Default: us-east-1
    Description: AWS region for AI provider services
  
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Bedrock model ID
  
  SagemakerEndpointName:
    Type: String
    Default: ''
    Description: Sagemaker endpoint name
  
  HuggingfaceModelName:
    Type: String
    Default: microsoft/DialoGPT-medium
    Description: Huggingface model name
  
  HuggingfaceSecretArn:
    Type: String
    Default: ''
    Description: ARN of the Huggingface API token secret
  
  ConfidenceThreshold:
    Type: Number
    Default: 0.8
    Description: Confidence threshold for AI-powered matching decisions
  
  SemanticThreshold:
    Type: Number
    Default: 0.85
    Description: Semantic similarity threshold for field matching
  
  EnablePerformanceOptimization:
    Type: String
    Default: 'true'
    Description: Enable performance optimization features

Conditions:
  HasCognitoAuth: !Not [!Equals [!Ref CognitoUserPoolArn, '']]
  UseAIProvider: !Not [!Equals [!Ref AIProviderType, 'none']]
  HasHuggingfaceSecret: !Not [!Equals [!Ref HuggingfaceSecretArn, '']]

Resources:
  #############################################################
  # Lambda Functions
  #############################################################
  DocumentProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${EnvironmentName}-trade-reconciliation-document-processor
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 60
      MemorySize: 1024
      Role: !ImportValue
        Fn::Sub: ${EnvironmentName}-document-processor-role-arn
      Code:
        ZipFile: |
          // This is a placeholder. The actual code will be deployed separately.
          exports.handler = async (event) => {
            console.log('Document processor placeholder function');
            return { statusCode: 200, body: JSON.stringify({message: 'Document processor placeholder function'}) };
          };
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName
          DOCUMENTS_BUCKET: !ImportValue
            Fn::Sub: ${EnvironmentName}-documents-bucket
          SOURCE_TRADE_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-source-trade-table
          TARGET_TRADE_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-target-trade-table
          DOCUMENT_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-document-table
          # AI Provider Configuration
          AI_PROVIDER_TYPE: !Ref AIProviderType
          DECISION_MODE: !Ref DecisionMode
          AI_PROVIDER_REGION: !Ref AIProviderRegion
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          SAGEMAKER_ENDPOINT_NAME: !Ref SagemakerEndpointName
          HUGGINGFACE_MODEL_NAME: !Ref HuggingfaceModelName
          HUGGINGFACE_SECRET_ARN: !Ref HuggingfaceSecretArn
          CONFIDENCE_THRESHOLD: !Ref ConfidenceThreshold
          SEMANTIC_THRESHOLD: !Ref SemanticThreshold
          ENABLE_PERFORMANCE_OPTIMIZATION: !Ref EnablePerformanceOptimization
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  ReconciliationEngineFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${EnvironmentName}-trade-reconciliation-engine
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 300
      MemorySize: 2048
      Role: !ImportValue
        Fn::Sub: ${EnvironmentName}-reconciliation-engine-role-arn
      Code:
        ZipFile: |
          // This is a placeholder. The actual code will be deployed separately.
          exports.handler = async (event) => {
            console.log('Reconciliation engine placeholder function');
            return { statusCode: 200, body: JSON.stringify({message: 'Reconciliation engine placeholder function'}) };
          };
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName
          SOURCE_TRADE_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-source-trade-table
          TARGET_TRADE_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-target-trade-table
          MATCH_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-match-table
          RECONCILIATION_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-reconciliation-table
          # AI Provider Configuration
          AI_PROVIDER_TYPE: !Ref AIProviderType
          DECISION_MODE: !Ref DecisionMode
          AI_PROVIDER_REGION: !Ref AIProviderRegion
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          SAGEMAKER_ENDPOINT_NAME: !Ref SagemakerEndpointName
          HUGGINGFACE_MODEL_NAME: !Ref HuggingfaceModelName
          HUGGINGFACE_SECRET_ARN: !Ref HuggingfaceSecretArn
          CONFIDENCE_THRESHOLD: !Ref ConfidenceThreshold
          SEMANTIC_THRESHOLD: !Ref SemanticThreshold
          ENABLE_PERFORMANCE_OPTIMIZATION: !Ref EnablePerformanceOptimization
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  ApiHandlerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub ${EnvironmentName}-trade-reconciliation-api-handler
      Handler: index.handler
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 512
      Role: !ImportValue
        Fn::Sub: ${EnvironmentName}-api-handler-role-arn
      Code:
        ZipFile: |
          // This is a placeholder. The actual code will be deployed separately.
          exports.handler = async (event) => {
            console.log('API handler placeholder function');
            return { statusCode: 200, body: JSON.stringify({message: 'API handler placeholder function'}) };
          };
      Environment:
        Variables:
          ENVIRONMENT_NAME: !Ref EnvironmentName
          DOCUMENTS_BUCKET: !ImportValue
            Fn::Sub: ${EnvironmentName}-documents-bucket
          SOURCE_TRADE_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-source-trade-table
          TARGET_TRADE_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-target-trade-table
          DOCUMENT_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-document-table
          MATCH_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-match-table
          RECONCILIATION_TABLE: !ImportValue
            Fn::Sub: ${EnvironmentName}-reconciliation-table
          DOCUMENT_PROCESSOR_FUNCTION: !Ref DocumentProcessorFunction
          RECONCILIATION_ENGINE_FUNCTION: !Ref ReconciliationEngineFunction
          # AI Provider Configuration
          AI_PROVIDER_TYPE: !Ref AIProviderType
          DECISION_MODE: !Ref DecisionMode
          AI_PROVIDER_REGION: !Ref AIProviderRegion
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          SAGEMAKER_ENDPOINT_NAME: !Ref SagemakerEndpointName
          HUGGINGFACE_MODEL_NAME: !Ref HuggingfaceModelName
          HUGGINGFACE_SECRET_ARN: !Ref HuggingfaceSecretArn
          CONFIDENCE_THRESHOLD: !Ref ConfidenceThreshold
          SEMANTIC_THRESHOLD: !Ref SemanticThreshold
          ENABLE_PERFORMANCE_OPTIMIZATION: !Ref EnablePerformanceOptimization
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # Lambda Permissions
  #############################################################
  ApiHandlerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt ApiHandlerFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

  #############################################################
  # Lambda S3 Trigger
  #############################################################
  DocumentProcessorS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DocumentProcessorFunction.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::${EnvironmentName}-trade-reconciliation-documents

  #############################################################
  # API Gateway
  #############################################################
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${EnvironmentName}-trade-reconciliation-api
      Description: API for Trade Reconciliation Solution
      EndpointConfiguration:
        Types:
          - REGIONAL
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  ApiGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: !If [HasCognitoAuth, COGNITO_USER_POOLS, NONE]
      AuthorizerId: !If [HasCognitoAuth, !Ref ApiGatewayAuthorizer, !Ref "AWS::NoValue"]
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiHandlerFunction.Arn}/invocations
      ResourceId: !GetAtt ApiGateway.RootResourceId
      RestApiId: !Ref ApiGateway

  ApiGatewayProxy:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: '{proxy+}'
      RestApiId: !Ref ApiGateway

  ApiGatewayProxyMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: !If [HasCognitoAuth, COGNITO_USER_POOLS, NONE]
      AuthorizerId: !If [HasCognitoAuth, !Ref ApiGatewayAuthorizer, !Ref "AWS::NoValue"]
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ApiHandlerFunction.Arn}/invocations
      ResourceId: !Ref ApiGatewayProxy
      RestApiId: !Ref ApiGateway
      RequestParameters:
        method.request.path.proxy: true

  ApiGatewayAuthorizer:
    Type: AWS::ApiGateway::Authorizer
    Condition: HasCognitoAuth
    Properties:
      Name: !Sub ${EnvironmentName}-trade-reconciliation-cognito-authorizer
      RestApiId: !Ref ApiGateway
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      ProviderARNs:
        - !Ref CognitoUserPoolArn

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ApiGatewayRootMethod
      - ApiGatewayProxyMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref ApiStageName
      StageDescription:
        AccessLogSetting:
          DestinationArn: !GetAtt ApiGatewayAccessLogGroup.Arn
          Format: '{"requestId":"$context.requestId", "ip":"$context.identity.sourceIp", "caller":"$context.identity.caller", "user":"$context.identity.user", "requestTime":"$context.requestTime", "httpMethod":"$context.httpMethod", "resourcePath":"$context.resourcePath", "status":"$context.status", "protocol":"$context.protocol", "responseLength":"$context.responseLength"}'
        MethodSettings:
          - ResourcePath: '/*'
            HttpMethod: '*'
            MetricsEnabled: true
            DataTraceEnabled: true
            LoggingLevel: INFO

  ApiGatewayAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/apigateway/${EnvironmentName}-trade-reconciliation-api-access-logs
      RetentionInDays: 90

  #############################################################
  # CloudWatch Logs
  #############################################################
  DocumentProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DocumentProcessorFunction}
      RetentionInDays: 90
  
  ReconciliationEngineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ReconciliationEngineFunction}
      RetentionInDays: 90
  
  ApiHandlerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiHandlerFunction}
      RetentionInDays: 90

Outputs:
  ApiEndpoint:
    Description: URL of the API Gateway endpoint
    Value: !Sub https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/
    Export:
      Name: !Sub ${EnvironmentName}-api-endpoint
  
  ApiId:
    Description: ID of the API Gateway
    Value: !Ref ApiGateway
    Export:
      Name: !Sub ${EnvironmentName}-api-id
  
  DocumentProcessorFunctionArn:
    Description: ARN of the document processor Lambda function
    Value: !GetAtt DocumentProcessorFunction.Arn
    Export:
      Name: !Sub ${EnvironmentName}-document-processor-function-arn
  
  ReconciliationEngineFunctionArn:
    Description: ARN of the reconciliation engine Lambda function
    Value: !GetAtt ReconciliationEngineFunction.Arn
    Export:
      Name: !Sub ${EnvironmentName}-reconciliation-engine-function-arn
  
  ApiHandlerFunctionArn:
    Description: ARN of the API handler Lambda function
    Value: !GetAtt ApiHandlerFunction.Arn
    Export:
      Name: !Sub ${EnvironmentName}-api-handler-function-arn