AWSTemplateFormatVersion: '2010-09-09'
Description: 'Trade Reconciliation Solution - Master Stack'

Parameters:
  TemplateS3Bucket:
    Type: String
    Description: Name of the S3 bucket containing nested CloudFormation templates
    
  TemplateS3Path:
    Type: String
    Default: trade-reconciliation
    Description: Path prefix in the S3 bucket where templates are stored
    
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  ApiStageName:
    Type: String
    Default: api
    Description: Name of the API Gateway stage
  
  EnableAuth:
    Type: String
    Default: 'false'
    Description: Enable Cognito authentication
    AllowedValues:
      - 'true'
      - 'false'
  
  AdminEmail:
    Type: String
    Description: Admin email address for Cognito user pool notifications
    Default: ''

  # AI Provider Configuration Parameters
  AIProviderType:
    Type: String
    Default: bedrock
    Description: AI provider to use for enhanced reconciliation
    AllowedValues:
      - bedrock
      - sagemaker
      - huggingface
      - none
  
  DecisionMode:
    Type: String
    Default: deterministic
    Description: Decision making approach for trade reconciliation
    AllowedValues:
      - deterministic
      - llm
      - hybrid
  
  AIProviderRegion:
    Type: String
    Default: us-east-1
    Description: AWS region for AI provider services
    AllowedValues:
      - us-east-1
      - us-west-2
      - eu-west-1
      - eu-central-1
      - ap-southeast-1
      - ap-northeast-1
      - me-central-1
      - me-south-1
  
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Bedrock model ID (when using Bedrock provider)
  
  SagemakerEndpointName:
    Type: String
    Default: ''
    Description: Sagemaker endpoint name (when using Sagemaker provider)
  
  HuggingfaceModelName:
    Type: String
    Default: microsoft/DialoGPT-medium
    Description: Huggingface model name (when using Huggingface provider)
  
  HuggingfaceApiToken:
    Type: String
    Default: ''
    NoEcho: true
    Description: Huggingface API token (stored in Secrets Manager)
  
  ConfidenceThreshold:
    Type: Number
    Default: 0.8
    MinValue: 0.1
    MaxValue: 1.0
    Description: Confidence threshold for AI-powered matching decisions
  
  SemanticThreshold:
    Type: Number
    Default: 0.85
    MinValue: 0.1
    MaxValue: 1.0
    Description: Semantic similarity threshold for field matching
  
  EnablePerformanceOptimization:
    Type: String
    Default: 'true'
    Description: Enable performance optimization features (batching, caching)
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  EnableAuthCondition: !Equals [!Ref EnableAuth, 'true']
  HasAdminEmail: !Not [!Equals [!Ref AdminEmail, '']]
  HasPath: !Not [!Equals [!Ref TemplateS3Path, '']]
  
  # AI Provider Conditions
  UseBedrockProvider: !Equals [!Ref AIProviderType, 'bedrock']
  UseSagemakerProvider: !Equals [!Ref AIProviderType, 'sagemaker']
  UseHuggingfaceProvider: !Equals [!Ref AIProviderType, 'huggingface']
  UseAIProvider: !Not [!Equals [!Ref AIProviderType, 'none']]
  UseLLMMode: !Or [!Equals [!Ref DecisionMode, 'llm'], !Equals [!Ref DecisionMode, 'hybrid']]
  
  # Regional AI Service Availability Conditions
  BedrockAvailableInRegion: !Or
    - !Equals [!Ref AIProviderRegion, 'us-east-1']
    - !Equals [!Ref AIProviderRegion, 'us-west-2']
    - !Equals [!Ref AIProviderRegion, 'eu-west-1']
    - !Equals [!Ref AIProviderRegion, 'eu-central-1']
    - !Equals [!Ref AIProviderRegion, 'ap-southeast-1']
    - !Equals [!Ref AIProviderRegion, 'ap-northeast-1']
  
  SagemakerAvailableInRegion: !Or
    - !Equals [!Ref AIProviderRegion, 'us-east-1']
    - !Equals [!Ref AIProviderRegion, 'us-west-2']
    - !Equals [!Ref AIProviderRegion, 'eu-west-1']
    - !Equals [!Ref AIProviderRegion, 'eu-central-1']
    - !Equals [!Ref AIProviderRegion, 'ap-southeast-1']
    - !Equals [!Ref AIProviderRegion, 'ap-northeast-1']
    - !Equals [!Ref AIProviderRegion, 'me-central-1']
    - !Equals [!Ref AIProviderRegion, 'me-south-1']
  
  # Validation Conditions
  ValidBedrockConfig: !And [!Condition UseBedrockProvider, !Condition BedrockAvailableInRegion]
  ValidSagemakerConfig: !And [!Condition UseSagemakerProvider, !Condition SagemakerAvailableInRegion, !Not [!Equals [!Ref SagemakerEndpointName, '']]]
  ValidHuggingfaceConfig: !And [!Condition UseHuggingfaceProvider, !Not [!Equals [!Ref HuggingfaceApiToken, '']]]
  
  HasHuggingfaceToken: !Not [!Equals [!Ref HuggingfaceApiToken, '']]
  EnablePerformanceFeatures: !Equals [!Ref EnablePerformanceOptimization, 'true']

Resources:
  #############################################################
  # Huggingface API Token Secret (Conditional)
  #############################################################
  HuggingfaceApiTokenSecret:
    Type: AWS::SecretsManager::Secret
    Condition: HasHuggingfaceToken
    Properties:
      Name: !Sub ${EnvironmentName}-huggingface-api-token
      Description: Huggingface API token for AI model access
      SecretString: !Sub |
        {
          "api_token": "${HuggingfaceApiToken}"
        }
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # Core Infrastructure Stack
  #############################################################
  CoreInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If
        - HasPath
        - !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/core-infrastructure.yaml
        - !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/core-infrastructure.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AIProviderType: !Ref AIProviderType
        AIProviderRegion: !Ref AIProviderRegion
        UseAIProvider: !If [UseAIProvider, 'true', 'false']
        HuggingfaceSecretArn: !If [HasHuggingfaceToken, !Ref HuggingfaceApiTokenSecret, '']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # Authentication Stack (Conditional)
  #############################################################
  AuthenticationStack:
    Type: AWS::CloudFormation::Stack
    Condition: EnableAuthCondition
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/authentication.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AdminEmail: !If [HasAdminEmail, !Ref AdminEmail, 'admin@example.com']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # API and Lambda Stack
  #############################################################
  ApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CoreInfrastructureStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/api-lambda.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiStageName: !Ref ApiStageName
        CognitoUserPoolArn: !If 
          - EnableAuthCondition
          - !GetAtt AuthenticationStack.Outputs.UserPoolArn
          - ''
        # AI Provider Configuration
        AIProviderType: !Ref AIProviderType
        DecisionMode: !Ref DecisionMode
        AIProviderRegion: !Ref AIProviderRegion
        BedrockModelId: !Ref BedrockModelId
        SagemakerEndpointName: !Ref SagemakerEndpointName
        HuggingfaceModelName: !Ref HuggingfaceModelName
        HuggingfaceSecretArn: !If [HasHuggingfaceToken, !Ref HuggingfaceApiTokenSecret, '']
        ConfidenceThreshold: !Ref ConfidenceThreshold
        SemanticThreshold: !Ref SemanticThreshold
        EnablePerformanceOptimization: !Ref EnablePerformanceOptimization
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # Frontend Stack (Conditional)
  #############################################################
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Condition: EnableAuthCondition
    DependsOn:
      - ApiLambdaStack
      - AuthenticationStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/frontend-amplify.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiEndpoint: !GetAtt ApiLambdaStack.Outputs.ApiEndpoint
        UserPoolId: !GetAtt AuthenticationStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt AuthenticationStack.Outputs.UserPoolClientId
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # Monitoring and Alerting Stack
  #############################################################
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ApiLambdaStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/monitoring.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiGatewayId: !GetAtt ApiLambdaStack.Outputs.ApiId
        ApiHandlerFunctionName: !Sub ${EnvironmentName}-trade-reconciliation-api-handler
        DocumentProcessorFunctionName: !Sub ${EnvironmentName}-trade-reconciliation-document-processor
        ReconciliationEngineFunctionName: !Sub ${EnvironmentName}-trade-reconciliation-engine
        NotificationEmail: !If [HasAdminEmail, !Ref AdminEmail, '']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

  #############################################################
  # Backup and Disaster Recovery Stack
  #############################################################
  BackupDRStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CoreInfrastructureStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/backup-dr.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        BackupRetentionDays: 30
        PointInTimeRecoveryEnabled: 'true'
        S3ReplicationEnabled: 'true'
        DisasterRecoveryRegion: 'us-west-2'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  ApiEndpoint:
    Description: URL of the API Gateway endpoint
    Value: !GetAtt ApiLambdaStack.Outputs.ApiEndpoint
  
  DashboardURL:
    Description: URL of the CloudWatch Dashboard
    Value: !GetAtt MonitoringStack.Outputs.DashboardURL
    
  BackupVaultName:
    Description: Name of the backup vault
    Value: !GetAtt BackupDRStack.Outputs.BackupVaultName
    
  DisasterRecoveryTopicArn:
    Description: ARN of the disaster recovery SNS topic
    Value: !GetAtt BackupDRStack.Outputs.DisasterRecoveryTopicArn
  
  DocumentsBucketName:
    Description: Name of the S3 bucket for document storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.DocumentsBucketName
  
  SourceTradeTableName:
    Description: Name of the source trades DynamoDB table
    Value: !GetAtt CoreInfrastructureStack.Outputs.SourceTradeTableName
  
  TargetTradeTableName:
    Description: Name of the target trades DynamoDB table
    Value: !GetAtt CoreInfrastructureStack.Outputs.TargetTradeTableName
  
  DocumentTableName:
    Description: Name of the documents DynamoDB table
    Value: !GetAtt CoreInfrastructureStack.Outputs.DocumentTableName
  
  ReconciliationTableName:
    Description: Name of the reconciliations DynamoDB table
    Value: !GetAtt CoreInfrastructureStack.Outputs.ReconciliationTableName
  
  MatchTableName:
    Description: Name of the matches DynamoDB table
    Value: !GetAtt CoreInfrastructureStack.Outputs.MatchTableName
  
  UserPoolId:
    Condition: EnableAuthCondition
    Description: ID of the Cognito User Pool
    Value: !GetAtt AuthenticationStack.Outputs.UserPoolId
  
  UserPoolClientId:
    Condition: EnableAuthCondition
    Description: ID of the Cognito User Pool Client
    Value: !GetAtt AuthenticationStack.Outputs.UserPoolClientId
  
  FrontendURL:
    Condition: EnableAuthCondition
    Description: URL of the frontend hosted on Amplify
    Value: !GetAtt FrontendStack.Outputs.AmplifyAppURL
