AWSTemplateFormatVersion: '2010-09-09'
Description: 'Trade Reconciliation Solution - Monitoring and Alerting Resources'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  NotificationEmail:
    Type: String
    Description: Email address for alarm notifications
    Default: ''

  ApiGatewayId:
    Type: String
    Description: ID of the API Gateway
  
  ApiHandlerFunctionName:
    Type: String
    Description: Name of the API handler Lambda function
  
  DocumentProcessorFunctionName:
    Type: String
    Description: Name of the document processor Lambda function
  
  ReconciliationEngineFunctionName:
    Type: String
    Description: Name of the reconciliation engine Lambda function

Conditions:
  HasNotificationEmail: !Not [!Equals [!Ref NotificationEmail, '']]

Resources:
  #############################################################
  # SNS Topic for Alarms
  #############################################################
  AlarmTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub ${EnvironmentName}-trade-reconciliation-alarms
      TopicName: !Sub ${EnvironmentName}-trade-reconciliation-alarms

  AlarmTopicSubscription:
    Type: AWS::SNS::Subscription
    Condition: HasNotificationEmail
    Properties:
      Protocol: email
      TopicArn: !Ref AlarmTopic
      Endpoint: !Ref NotificationEmail

  #############################################################
  # CloudWatch Dashboard
  #############################################################
  MainDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub ${EnvironmentName}-trade-reconciliation
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/ApiGateway", "Count", "ApiName", "${EnvironmentName}-trade-reconciliation-api" ],
                  [ "AWS/ApiGateway", "4XXError", "ApiName", "${EnvironmentName}-trade-reconciliation-api" ],
                  [ "AWS/ApiGateway", "5XXError", "ApiName", "${EnvironmentName}-trade-reconciliation-api" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Gateway Requests",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${ApiHandlerFunctionName}" ],
                  [ "AWS/Lambda", "Errors", "FunctionName", "${ApiHandlerFunctionName}" ],
                  [ "AWS/Lambda", "Throttles", "FunctionName", "${ApiHandlerFunctionName}" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "API Handler Lambda",
                "period": 300,
                "stat": "Sum"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${DocumentProcessorFunctionName}" ],
                  [ "AWS/Lambda", "Errors", "FunctionName", "${DocumentProcessorFunctionName}" ],
                  [ "AWS/Lambda", "Throttles", "FunctionName", "${DocumentProcessorFunctionName}" ],
                  [ "AWS/Lambda", "Duration", "FunctionName", "${DocumentProcessorFunctionName}", { "stat": "Average" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Document Processor Lambda",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/Lambda", "Invocations", "FunctionName", "${ReconciliationEngineFunctionName}" ],
                  [ "AWS/Lambda", "Errors", "FunctionName", "${ReconciliationEngineFunctionName}" ],
                  [ "AWS/Lambda", "Throttles", "FunctionName", "${ReconciliationEngineFunctionName}" ],
                  [ "AWS/Lambda", "Duration", "FunctionName", "${ReconciliationEngineFunctionName}", { "stat": "Average" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "Reconciliation Engine Lambda",
                "period": 300
              }
            },
            {
              "type": "text",
              "x": 0,
              "y": 12,
              "width": 24,
              "height": 3,
              "properties": {
                "markdown": "# Trade Reconciliation System Dashboard\n\nThis dashboard provides monitoring for key components of the Trade Reconciliation System:\n\n* **API Gateway:** Request counts, 4XX and 5XX errors\n* **Lambda Functions:** Invocations, errors, throttles, and duration metrics\n* **DynamoDB Tables:** Read/write capacity units, throttle events\n\nAlarms are configured to notify when critical thresholds are breached."
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 15,
              "width": 24,
              "height": 6,
              "properties": {
                "metrics": [
                  [ { "expression": "SEARCH('{AWS/DynamoDB,TableName} MetricName=\"SuccessfulRequestLatency\"', 'Average', 300)", "label": "Average Latency", "id": "e1" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Latency",
                "period": 300
              }
            }
          ]
        }

  #############################################################
  # CloudWatch Alarms
  #############################################################
  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-api-gateway-5xx-errors
      AlarmDescription: Alarm when API Gateway returns 5XX errors
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Dimensions:
        - Name: ApiName
          Value: !Sub ${EnvironmentName}-trade-reconciliation-api
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic

  ApiHandlerErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-api-handler-errors
      AlarmDescription: Alarm when API Handler Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApiHandlerFunctionName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic

  DocumentProcessorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-document-processor-errors
      AlarmDescription: Alarm when Document Processor Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref DocumentProcessorFunctionName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic

  ReconciliationEngineErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-reconciliation-engine-errors
      AlarmDescription: Alarm when Reconciliation Engine Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref ReconciliationEngineFunctionName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 5
      Threshold: 3
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic

  ReconciliationEngineDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-reconciliation-engine-duration
      AlarmDescription: Alarm when Reconciliation Engine Lambda function duration is high
      MetricName: Duration
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref ReconciliationEngineFunctionName
      Statistic: Average
      Period: 60
      EvaluationPeriods: 3
      Threshold: 30000  # 30 seconds
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmTopic
      OKActions:
        - !Ref AlarmTopic

Outputs:
  DashboardURL:
    Description: URL of the CloudWatch Dashboard
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MainDashboard}
    Export:
      Name: !Sub ${EnvironmentName}-cloudwatch-dashboard-url
  
  AlarmTopicArn:
    Description: ARN of the SNS topic for alarms
    Value: !Ref AlarmTopic
    Export:
      Name: !Sub ${EnvironmentName}-alarm-topic-arn
