AWSTemplateFormatVersion: '2010-09-09'
Description: 'Trade Reconciliation Solution - EU Region Master Stack'

Parameters:
  TemplateS3Bucket:
    Type: String
    Description: Name of the S3 bucket containing nested CloudFormation templates
    
  TemplateS3Path:
    Type: String
    Default: trade-reconciliation
    Description: Path prefix in the S3 bucket where templates are stored
    
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, test, prod)
    AllowedValues:
      - dev
      - test
      - prod
  
  ApiStageName:
    Type: String
    Default: api
    Description: Name of the API Gateway stage
  
  EnableAuth:
    Type: String
    Default: 'false'
    Description: Enable Cognito authentication
    AllowedValues:
      - 'true'
      - 'false'
  
  AdminEmail:
    Type: String
    Description: Admin email address for Cognito user pool notifications
    Default: ''

  # EU-Specific AI Provider Configuration
  AIProviderType:
    Type: String
    Default: bedrock
    Description: AI provider to use for enhanced reconciliation
    AllowedValues:
      - bedrock
      - sagemaker
      - huggingface
      - none
  
  DecisionMode:
    Type: String
    Default: deterministic
    Description: Decision making approach for trade reconciliation
    AllowedValues:
      - deterministic
      - llm
      - hybrid
  
  AIProviderRegion:
    Type: String
    Default: eu-west-1
    Description: AWS region for AI provider services
    AllowedValues:
      - eu-west-1
      - eu-central-1
  
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Bedrock model ID (when using Bedrock provider)
    AllowedValues:
      - anthropic.claude-3-sonnet-20240229-v1:0
      - anthropic.claude-3-haiku-20240307-v1:0
      - anthropic.claude-instant-v1
      - amazon.titan-text-express-v1
  
  SagemakerEndpointName:
    Type: String
    Default: ''
    Description: Sagemaker endpoint name (when using Sagemaker provider)
  
  HuggingfaceModelName:
    Type: String
    Default: microsoft/DialoGPT-medium
    Description: Huggingface model name (when using Huggingface provider)
  
  HuggingfaceApiToken:
    Type: String
    Default: ''
    NoEcho: true
    Description: Huggingface API token (stored in Secrets Manager)
  
  ConfidenceThreshold:
    Type: Number
    Default: 0.8
    MinValue: 0.1
    MaxValue: 1.0
    Description: Confidence threshold for AI-powered matching decisions
  
  SemanticThreshold:
    Type: Number
    Default: 0.85
    MinValue: 0.1
    MaxValue: 1.0
    Description: Semantic similarity threshold for field matching
  
  EnablePerformanceOptimization:
    Type: String
    Default: 'true'
    Description: Enable performance optimization features (batching, caching)
    AllowedValues:
      - 'true'
      - 'false'
  
  # EU-Specific Compliance Parameters
  GDPRCompliance:
    Type: String
    Default: 'true'
    Description: Enable GDPR compliance features
    AllowedValues:
      - 'true'
      - 'false'
  
  DataResidencyRegion:
    Type: String
    Default: eu-west-1
    Description: Region for data residency compliance
    AllowedValues:
      - eu-west-1
      - eu-central-1

Conditions:
  EnableAuthCondition: !Equals [!Ref EnableAuth, 'true']
  HasAdminEmail: !Not [!Equals [!Ref AdminEmail, '']]
  HasPath: !Not [!Equals [!Ref TemplateS3Path, '']]
  
  # AI Provider Conditions
  UseBedrockProvider: !Equals [!Ref AIProviderType, 'bedrock']
  UseSagemakerProvider: !Equals [!Ref AIProviderType, 'sagemaker']
  UseHuggingfaceProvider: !Equals [!Ref AIProviderType, 'huggingface']
  UseAIProvider: !Not [!Equals [!Ref AIProviderType, 'none']]
  UseLLMMode: !Or [!Equals [!Ref DecisionMode, 'llm'], !Equals [!Ref DecisionMode, 'hybrid']]
  
  # Regional AI Service Availability Conditions
  BedrockAvailableInRegion: !Or
    - !Equals [!Ref AIProviderRegion, 'eu-west-1']
    - !Equals [!Ref AIProviderRegion, 'eu-central-1']
  
  # Validation Conditions
  ValidBedrockConfig: !And [!Condition UseBedrockProvider, !Condition BedrockAvailableInRegion]
  ValidSagemakerConfig: !And [!Condition UseSagemakerProvider, !Not [!Equals [!Ref SagemakerEndpointName, '']]]
  ValidHuggingfaceConfig: !And [!Condition UseHuggingfaceProvider, !Not [!Equals [!Ref HuggingfaceApiToken, '']]]
  
  HasHuggingfaceToken: !Not [!Equals [!Ref HuggingfaceApiToken, '']]
  EnablePerformanceFeatures: !Equals [!Ref EnablePerformanceOptimization, 'true']
  EnableGDPRFeatures: !Equals [!Ref GDPRCompliance, 'true']
  IsEUWest1: !Equals [!Ref DataResidencyRegion, 'eu-west-1']

Rules:
  ValidateAIProviderConfiguration:
    RuleCondition: !Not [!Equals [!Ref AIProviderType, 'none']]
    Assertions:
      - Assert: !Or
          - !Equals [!Ref AIProviderType, 'bedrock']
          - !And [!Equals [!Ref AIProviderType, 'sagemaker'], !Not [!Equals [!Ref SagemakerEndpointName, '']]]
          - !And [!Equals [!Ref AIProviderType, 'huggingface'], !Not [!Equals [!Ref HuggingfaceApiToken, '']]]
        AssertDescription: "When using AI provider, appropriate configuration must be provided"
  
  ValidateDataResidency:
    RuleCondition: !Equals [!Ref GDPRCompliance, 'true']
    Assertions:
      - Assert: !Or
          - !Equals [!Ref DataResidencyRegion, 'eu-west-1']
          - !Equals [!Ref DataResidencyRegion, 'eu-central-1']
        AssertDescription: "Data residency must be within EU regions for GDPR compliance"

Resources:
  #############################################################
  # Huggingface API Token Secret (Conditional)
  #############################################################
  HuggingfaceApiTokenSecret:
    Type: AWS::SecretsManager::Secret
    Condition: HasHuggingfaceToken
    Properties:
      Name: !Sub ${EnvironmentName}-huggingface-api-token
      Description: Huggingface API token for AI model access
      SecretString: !Sub |
        {
          "api_token": "${HuggingfaceApiToken}"
        }
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

  #############################################################
  # Core Infrastructure Stack
  #############################################################
  CoreInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !If
        - HasPath
        - !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/core-infrastructure.yaml
        - !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/core-infrastructure.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AIProviderType: !Ref AIProviderType
        AIProviderRegion: !Ref AIProviderRegion
        UseAIProvider: !If [UseAIProvider, 'true', 'false']
        HuggingfaceSecretArn: !If [HasHuggingfaceToken, !Ref HuggingfaceApiTokenSecret, '']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

  #############################################################
  # Authentication Stack (Conditional)
  #############################################################
  AuthenticationStack:
    Type: AWS::CloudFormation::Stack
    Condition: EnableAuthCondition
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/authentication.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        AdminEmail: !If [HasAdminEmail, !Ref AdminEmail, 'admin@example.com']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

  #############################################################
  # API and Lambda Stack
  #############################################################
  ApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CoreInfrastructureStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/api-lambda.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiStageName: !Ref ApiStageName
        CognitoUserPoolArn: !If 
          - EnableAuthCondition
          - !GetAtt AuthenticationStack.Outputs.UserPoolArn
          - ''
        # AI Provider Configuration (EU-specific)
        AIProviderType: !Ref AIProviderType
        DecisionMode: !Ref DecisionMode
        AIProviderRegion: !Ref AIProviderRegion
        BedrockModelId: !Ref BedrockModelId
        SagemakerEndpointName: !Ref SagemakerEndpointName
        HuggingfaceModelName: !Ref HuggingfaceModelName
        HuggingfaceSecretArn: !If [HasHuggingfaceToken, !Ref HuggingfaceApiTokenSecret, '']
        ConfidenceThreshold: !Ref ConfidenceThreshold
        SemanticThreshold: !Ref SemanticThreshold
        EnablePerformanceOptimization: !Ref EnablePerformanceOptimization
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

  #############################################################
  # Frontend Stack (Conditional)
  #############################################################
  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Condition: EnableAuthCondition
    DependsOn:
      - ApiLambdaStack
      - AuthenticationStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/frontend-amplify.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiEndpoint: !GetAtt ApiLambdaStack.Outputs.ApiEndpoint
        UserPoolId: !GetAtt AuthenticationStack.Outputs.UserPoolId
        UserPoolClientId: !GetAtt AuthenticationStack.Outputs.UserPoolClientId
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

  #############################################################
  # Monitoring and Alerting Stack
  #############################################################
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - ApiLambdaStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/monitoring.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ApiGatewayId: !GetAtt ApiLambdaStack.Outputs.ApiId
        ApiHandlerFunctionName: !Sub ${EnvironmentName}-trade-reconciliation-api-handler
        DocumentProcessorFunctionName: !Sub ${EnvironmentName}-trade-reconciliation-document-processor
        ReconciliationEngineFunctionName: !Sub ${EnvironmentName}-trade-reconciliation-engine
        NotificationEmail: !If [HasAdminEmail, !Ref AdminEmail, '']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

  #############################################################
  # Backup and Disaster Recovery Stack
  #############################################################
  BackupDRStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CoreInfrastructureStack
    Properties:
      TemplateURL: !Sub https://s3.${AWS::Region}.amazonaws.com/${TemplateS3Bucket}/${TemplateS3Path}/backup-dr.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        BackupRetentionDays: 30
        PointInTimeRecoveryEnabled: 'true'
        S3ReplicationEnabled: 'true'
        DisasterRecoveryRegion: !If [IsEUWest1, 'eu-central-1', 'eu-west-1']
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Region
          Value: EU
        - Key: GDPRCompliant
          Value: !Ref GDPRCompliance

Outputs:
  ApiEndpoint:
    Description: URL of the API Gateway endpoint
    Value: !GetAtt ApiLambdaStack.Outputs.ApiEndpoint
  
  DashboardURL:
    Description: URL of the CloudWatch Dashboard
    Value: !GetAtt MonitoringStack.Outputs.DashboardURL
    
  BackupVaultName:
    Description: Name of the backup vault
    Value: !GetAtt BackupDRStack.Outputs.BackupVaultName
    
  DisasterRecoveryTopicArn:
    Description: ARN of the disaster recovery SNS topic
    Value: !GetAtt BackupDRStack.Outputs.DisasterRecoveryTopicArn
  
  DocumentsBucketName:
    Description: Name of the S3 bucket for document storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.DocumentsBucketName
  
  AIProviderConfiguration:
    Description: AI provider configuration summary
    Value: !Sub |
      Provider: ${AIProviderType}
      Region: ${AIProviderRegion}
      Decision Mode: ${DecisionMode}
      Bedrock Model: ${BedrockModelId}
      Sagemaker Endpoint: ${SagemakerEndpointName}
  
  RegionalDeploymentInfo:
    Description: Regional deployment information
    Value: !Sub |
      Deployed in EU region (${AWS::Region})
      AI Provider: ${AIProviderType}
      Data Residency: ${DataResidencyRegion}
      GDPR Compliance: ${GDPRCompliance}
      DR Region: ${BackupDRStack.Outputs.DisasterRecoveryRegion}
  
  ComplianceInfo:
    Description: Compliance and data residency information
    Value: !Sub |
      GDPR Compliance: ${GDPRCompliance}
      Data Residency Region: ${DataResidencyRegion}
      All data stored within EU boundaries
  
  UserPoolId:
    Condition: EnableAuthCondition
    Description: ID of the Cognito User Pool
    Value: !GetAtt AuthenticationStack.Outputs.UserPoolId
  
  UserPoolClientId:
    Condition: EnableAuthCondition
    Description: ID of the Cognito User Pool Client
    Value: !GetAtt AuthenticationStack.Outputs.UserPoolClientId
  
  FrontendURL:
    Condition: EnableAuthCondition
    Description: URL of the frontend hosted on Amplify
    Value: !GetAtt FrontendStack.Outputs.AmplifyAppURL