default_agent: trade_matching_agent
agents:
  trade_matching_agent:
    name: trade_matching_agent
    entrypoint: /Users/koushald/ai-trade-matching-system-2/deployment/trade_matching/trade_matching_agent_strands.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/koushald/ai-trade-matching-system-2/deployment/trade_matching
    aws:
      execution_role: arn:aws:iam::401552979575:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-e4a41906cf
      execution_role_auto_create: false
      account: '401552979575'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-401552979575-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: trade_matching_agent-3aAvK64dQz
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:runtime/trade_matching_agent-3aAvK64dQz
      agent_session_id: 25e3b5da-10a7-4964-9da3-4fe4a0e8d260
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: trade_matching_agent_mem-SxPFir3bbF
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:401552979575:memory/trade_matching_agent_mem-SxPFir3bbF
      memory_name: trade_matching_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
