AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master template for Trade Reconciliation System - Deploys all components'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name for resource naming

  ApiGatewayStageName:
    Type: String
    Default: api
    Description: Stage name for API Gateway deployment

  RepositoryUrl:
    Type: String
    Description: 'Git repository URL (HTTPS) for frontend code'
    Default: https://github.com/username/trade-reconciliation-frontend.git

  RepositoryBranch:
    Type: String
    Description: 'Git repository branch to deploy'
    Default: main

  AccessToken:
    Type: String
    Description: 'Personal access token for the Git repository'
    NoEcho: true

  S3BucketForTemplates:
    Type: String
    Description: 'S3 bucket to store nested CloudFormation templates'
    
  S3PrefixForTemplates:
    Type: String
    Description: 'S3 prefix (folder) for nested CloudFormation templates'
    Default: 'cloudformation-templates/'
    
  CreateCustomCFNS3NotificationFunction:
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
    Description: 'Create the custom CloudFormation S3 notification function if it does not exist'

Conditions:
  CreateCFNS3NotificationFunction: !Equals [!Ref CreateCustomCFNS3NotificationFunction, 'true']
  
Resources:
  # Custom resource Lambda for S3 event notifications
  CFNS3NotificationFunction:
    Type: AWS::Lambda::Function
    Condition: CreateCFNS3NotificationFunction
    Properties:
      FunctionName: cfn-s3-notification
      Description: A Lambda function to configure S3 event notifications via CloudFormation
      Handler: index.handler
      Role: !GetAtt CFNS3NotificationRole.Arn
      Runtime: nodejs16.x
      Timeout: 30
      Code:
        ZipFile: |
          const AWS = require('aws-sdk');
          const s3 = new AWS.S3();
          
          exports.handler = async (event, context) => {
            console.log('Event:', JSON.stringify(event));
            
            if (event.RequestType === 'Delete') {
              // On delete, we clear all notifications
              await s3.putBucketNotificationConfiguration({
                Bucket: event.ResourceProperties.BucketName,
                NotificationConfiguration: {}
              }).promise();
              
              await sendCloudFormationResponse(event, context, 'SUCCESS', {});
              return;
            }
            
            try {
              // On create/update, we configure the provided notification
              await s3.putBucketNotificationConfiguration({
                Bucket: event.ResourceProperties.BucketName,
                NotificationConfiguration: event.ResourceProperties.NotificationConfiguration
              }).promise();
              
              await sendCloudFormationResponse(event, context, 'SUCCESS', {});
            } catch (error) {
              console.error('Error setting S3 notification:', error);
              await sendCloudFormationResponse(event, context, 'FAILED', {}, error.message);
            }
          };
          
          async function sendCloudFormationResponse(event, context, responseStatus, responseData, reason) {
            const responseBody = JSON.stringify({
              Status: responseStatus,
              Reason: reason || 'See the details in CloudWatch Log Stream: ' + context.logStreamName,
              PhysicalResourceId: context.logStreamName,
              StackId: event.StackId,
              RequestId: event.RequestId,
              LogicalResourceId: event.LogicalResourceId,
              Data: responseData
            });
            
            console.log('Response Body:', responseBody);
            
            const https = require('https');
            const url = require('url');
            const parsedUrl = url.parse(event.ResponseURL);
            
            const options = {
              hostname: parsedUrl.hostname,
              port: 443,
              path: parsedUrl.path,
              method: 'PUT',
              headers: {
                'content-type': '',
                'content-length': responseBody.length
              }
            };
            
            return new Promise((resolve, reject) => {
              const req = https.request(options, (res) => {
                console.log('Status code:', res.statusCode);
                resolve();
              });
              
              req.on('error', (error) => {
                console.error('Error sending response:', error);
                reject(error);
              });
              
              req.write(responseBody);
              req.end();
            });
          }

  CFNS3NotificationRole:
    Type: AWS::IAM::Role
    Condition: CreateCFNS3NotificationFunction
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: S3NotificationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutBucketNotification
                  - s3:GetBucketNotification
                  - s3:PutBucketNotificationConfiguration
                  - s3:GetBucketNotificationConfiguration
                Resource: '*'

  # Core Infrastructure Stack (DynamoDB & S3)
  CoreInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketForTemplates}.s3.${AWS::Region}.amazonaws.com/${S3PrefixForTemplates}core-infrastructure.yaml
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: TradeReconciliation

  # API Lambda Stack
  ApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CoreInfrastructureStack
    Properties:
      TemplateURL: !Sub https://${S3BucketForTemplates}.s3.${AWS::Region}.amazonaws.com/${S3PrefixForTemplates}api-lambda.yaml
      Parameters:
        Environment: !Ref Environment
        BankTableName: !GetAtt CoreInfrastructureStack.Outputs.BankTableName
        CounterpartyTableName: !GetAtt CoreInfrastructureStack.Outputs.CounterpartyTableName
        MatchesTableName: !GetAtt CoreInfrastructureStack.Outputs.MatchesTableName
        DocumentBucketName: !GetAtt CoreInfrastructureStack.Outputs.DocumentBucketName
        ReportBucketName: !GetAtt CoreInfrastructureStack.Outputs.ReportBucketName
        ApiGatewayStageName: !Ref ApiGatewayStageName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: TradeReconciliation

  # Frontend Amplify Stack
  FrontendAmplifyStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ApiLambdaStack
    Properties:
      TemplateURL: !Sub https://${S3BucketForTemplates}.s3.${AWS::Region}.amazonaws.com/${S3PrefixForTemplates}frontend-amplify.yaml
      Parameters:
        Environment: !Ref Environment
        ApiEndpointUrl: !GetAtt ApiLambdaStack.Outputs.ApiGatewayEndpoint
        RepositoryUrl: !Ref RepositoryUrl
        RepositoryBranch: !Ref RepositoryBranch
        AccessToken: !Ref AccessToken
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: TradeReconciliation

Outputs:
  ApiEndpoint:
    Description: API Gateway Endpoint URL
    Value: !GetAtt ApiLambdaStack.Outputs.ApiGatewayEndpoint

  FrontendUrl:
    Description: URL of the deployed frontend application
    Value: !GetAtt FrontendAmplifyStack.Outputs.AppUrl

  DocumentBucketName:
    Description: Name of the S3 Bucket for Document Storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.DocumentBucketName

  ReportBucketName:
    Description: Name of the S3 Bucket for Report Storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.ReportBucketName

  BankTableName:
    Description: Name of the DynamoDB Table for Bank Trades
    Value: !GetAtt CoreInfrastructureStack.Outputs.BankTableName

  CounterpartyTableName:
    Description: Name of the DynamoDB Table for Counterparty Trades
    Value: !GetAtt CoreInfrastructureStack.Outputs.CounterpartyTableName

  MatchesTableName:
    Description: Name of the DynamoDB Table for Match Records
    Value: !GetAtt CoreInfrastructureStack.Outputs.MatchesTableName
