AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master template for Trade Reconciliation System - Simplified Version'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name for resource naming

  ApiGatewayStageName:
    Type: String
    Default: api
    Description: Stage name for API Gateway deployment

  S3BucketForTemplates:
    Type: String
    Description: 'S3 bucket to store nested CloudFormation templates'
    
  S3PrefixForTemplates:
    Type: String
    Description: 'S3 prefix (folder) for nested CloudFormation templates'
    Default: 'cloudformation-templates/'

Resources:
  # Core Infrastructure Stack (DynamoDB & S3)
  CoreInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketForTemplates}.s3.${AWS::Region}.amazonaws.com/${S3PrefixForTemplates}fixed-core-infrastructure.yaml
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: TradeReconciliation

  # API Lambda Stack - Using simplified template
  ApiLambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CoreInfrastructureStack
    Properties:
      TemplateURL: !Sub https://${S3BucketForTemplates}.s3.${AWS::Region}.amazonaws.com/${S3PrefixForTemplates}simplified-api-lambda.yaml
      Parameters:
        Environment: !Ref Environment
        BankTableName: !GetAtt CoreInfrastructureStack.Outputs.BankTableName
        CounterpartyTableName: !GetAtt CoreInfrastructureStack.Outputs.CounterpartyTableName
        MatchesTableName: !GetAtt CoreInfrastructureStack.Outputs.MatchesTableName
        DocumentBucketName: !GetAtt CoreInfrastructureStack.Outputs.DocumentBucketName
        ReportBucketName: !GetAtt CoreInfrastructureStack.Outputs.ReportBucketName
        ApiGatewayStageName: !Ref ApiGatewayStageName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: TradeReconciliation

Outputs:
  ApiEndpoint:
    Description: API Gateway Endpoint URL
    Value: !GetAtt ApiLambdaStack.Outputs.ApiGatewayEndpoint

  DocumentBucketName:
    Description: Name of the S3 Bucket for Document Storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.DocumentBucketName

  ReportBucketName:
    Description: Name of the S3 Bucket for Report Storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.ReportBucketName

  BankTableName:
    Description: Name of the DynamoDB Table for Bank Trades
    Value: !GetAtt CoreInfrastructureStack.Outputs.BankTableName

  CounterpartyTableName:
    Description: Name of the DynamoDB Table for Counterparty Trades
    Value: !GetAtt CoreInfrastructureStack.Outputs.CounterpartyTableName

  MatchesTableName:
    Description: Name of the DynamoDB Table for Match Records
    Value: !GetAtt CoreInfrastructureStack.Outputs.MatchesTableName