AWSTemplateFormatVersion: '2010-09-09'
Description: 'Super minimal template for Trade Reconciliation System - Core Infrastructure Only'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name for resource naming

Resources:
  # Core Infrastructure Stack (DynamoDB & S3)
  CoreInfrastructureStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://trade-reconciliation-system-us-west-2.s3.us-west-2.amazonaws.com/cloudformation-templates/fixed-core-infrastructure.yaml
      Parameters:
        Environment: !Ref Environment
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: System
          Value: TradeReconciliation

Outputs:
  DocumentBucketName:
    Description: Name of the S3 Bucket for Document Storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.DocumentBucketName

  ReportBucketName:
    Description: Name of the S3 Bucket for Report Storage
    Value: !GetAtt CoreInfrastructureStack.Outputs.ReportBucketName

  BankTableName:
    Description: Name of the DynamoDB Table for Bank Trades
    Value: !GetAtt CoreInfrastructureStack.Outputs.BankTableName

  CounterpartyTableName:
    Description: Name of the DynamoDB Table for Counterparty Trades
    Value: !GetAtt CoreInfrastructureStack.Outputs.CounterpartyTableName

  MatchesTableName:
    Description: Name of the DynamoDB Table for Match Records
    Value: !GetAtt CoreInfrastructureStack.Outputs.MatchesTableName